ci: IFS-2857 allowed the logs of failed build to be fetched

diff --git a/.github/workflows/docs_build_template.yml b/.github/workflows/docs_build_template.yml
--- a/.github/workflows/docs_build_template.yml
+++ b/.github/workflows/docs_build_template.yml
@@ -38,6 +38,8 @@ jobs:
 
       - name: Wait for documentation build completion (Run ID - ${{ steps.trigger_build.outputs.run_id }})
         uses: codex-/await-remote-run@v1.11.0
+        id: wait_for_completion
+        continue-on-error: true
         with:
           token: ${{ secrets.ANTORA_TRIGGER_TOKEN }}
           repo: isyfact.github.io
@@ -75,9 +77,14 @@ jobs:
             
              # Remove timestamps from the log file
             echo "Processing logs to remove timestamps..."
-            sed 's/^[0-9TZ:\.-]*Z //g' "$build_log_file" > "$build_log_file"_cleaned  
+            sed 's/^[0-9TZ:\.-]*Z //g' "$build_log_file" > "${build_log_file}_cleaned"
         
             # Display the cleaned logs
             echo "Cleaned Build Documentation logs:"
-            cat "$build_log_file"_cleaned
+            cat "${build_log_file}_cleaned"
+          fi
+          
+          # Fail the step if "exit code 1" is in the cleaned logs
+          if grep -q "exit code 1" "${build_log_file}_cleaned"; then
+            exit 1  
           fi
