IFS-2853: CVE Scan for Dependencies in Dependency Management (#32)
* ci: IFS-2853 added step for modifying POM file of isyfact-products-bom for scanning dependencyManagement

* ci: IFS-2853 installed xmllint

* ci: IFS-2853 added debug

* ci: IFS-2853 tested snyk test

* ci: IFS-2853 fixed awk command

* ci: IFS-2853 tested Snyk commands

* ci: IFS-2853 added documentation for cve scanning of Dependency Management

diff --git a/.github/workflows/maven_dependency_scan_template.yml b/.github/workflows/maven_dependency_scan_template.yml
--- a/.github/workflows/maven_dependency_scan_template.yml
+++ b/.github/workflows/maven_dependency_scan_template.yml
@@ -35,6 +35,11 @@ on:
         description: 'Severity threshold for Snyk scan'
         type: string
         default: 'critical'
+      scan-dependency-management:
+        required: false
+        description: 'Scan dependencies in dependencyManagement'
+        type: boolean
+        default: true
     secrets:
       SNYK_TOKEN:
         required: true
@@ -51,18 +56,100 @@ jobs:
         uses: actions/checkout@v4
         with:
           lfs: ${{ inputs.checkout-lfs }}
+
       - name: Setup Snyk
         uses: snyk/actions/setup@master
+
       - name: Setup JDK ${{ inputs.jdk-version }}
         uses: actions/setup-java@v4
         with:
           java-version: ${{ inputs.jdk-version }}
           distribution: temurin
           cache: maven
+
+      - name: Modify POM file of isyfact-products-bom for scanning dependencyManagement
+        if: ${{ inputs.scan-dependency-management }}
+        run: |
+          POM_FILE="isyfact-products-bom/pom.xml"
+          TEMP_DEPENDENCIES_FILE="dependencies_temp.xml"
+
+          # Check if the POM file exists
+          if [ ! -f "$POM_FILE" ]; then
+              echo "$POM_FILE not found. No need for scanning dependencyManagement."
+              exit 0 
+          fi
+
+          echo "$POM_FILE found. Modifying the POM file."
+
+          # Extract dependencies from dependencyManagement
+          echo "Installing xmllint..."
+          sudo apt-get install libxml2-utils
+          
+          echo "Extracting dependencies from dependencyManagement..."
+
+          DEPENDENCIES=$(xmllint --xpath "//*[local-name()='dependencyManagement']/*[local-name()='dependencies']/*[local-name()='dependency']" "$POM_FILE" 2>/dev/null)
+
+          if ! [[ "$DEPENDENCIES" ]]; then
+              echo "Warning: No dependencies found in dependencyManagement. Skipping modification."
+              exit 0
+          fi
+
+          # Exclude specific artifactIds
+          EXCLUDED_ARTIFACT_IDS=("spring-boot-dependencies")
+          for artifactId in "${EXCLUDED_ARTIFACT_IDS[@]}"; do
+              DEPENDENCIES=$(echo "$DEPENDENCIES" | sed -n '/<dependency>/,/<\/dependency>/ {
+                  H;
+                  /<\/dependency>/ {
+                      x;
+                      /<artifactId>'"$artifactId"'<\/artifactId>/d;
+                      p
+                  }
+              }')
+          done
+
+          # Remove <exclusions> blocks and extract only groupId and artifactId from <dependency>
+          DEPENDENCIES=$(echo "$DEPENDENCIES" | sed -n '
+            /<dependency>/,/<\/dependency>/ {
+            /<dependency>/p;
+            /<\/dependency>/p;
+            /<exclusions>/,/<\/exclusions>/d;  # Remove exclusions block
+            /<groupId>/p;                      # Only print groupId
+            /<artifactId>/p;                   # Only print artifactId
+          }')
+
+          # Insert extracted dependencies into the <dependencies> section right after </dependencyManagement>
+          echo "Inserting extracted dependencies into the POM file..."
+          echo "$DEPENDENCIES" > "$TEMP_DEPENDENCIES_FILE"
+          
+          awk -v depfile="$TEMP_DEPENDENCIES_FILE" '
+            /<\/dependencyManagement>/ {
+              print $0
+              print "<dependencies>"
+              while ((getline line < depfile) > 0) {
+                print line
+              }
+              print "</dependencies>"
+              next
+            }
+            { print $0 }
+          ' "$POM_FILE" > "$POM_FILE.tmp" && mv "$POM_FILE.tmp" "$POM_FILE"
+
+          if [[ $? -eq 0 ]]; then
+            echo "Dependencies successfully inserted into $POM_FILE"
+          else
+            echo "Failed to insert dependencies."
+            exit 1
+          fi
+
       - name: Run Snyk task
         run: |
           if [ "${{ inputs.perform-scan }}" = "true" ]; then
-            snyk test ${{ inputs.snyk-arguments }} --severity-threshold=${{ inputs.severity-threshold }} --target-reference=${{ inputs.snyk-reference }} --org=${{ inputs.snyk-organization }}
+            snyk test ${{ inputs.snyk-arguments }} \
+              --severity-threshold=${{ inputs.severity-threshold }} \
+              --target-reference=${{ inputs.snyk-reference }} \
+              --org=${{ inputs.snyk-organization }}
           else
-            snyk monitor ${{ inputs.snyk-arguments }} --target-reference=${{ inputs.snyk-reference }} --org=${{ inputs.snyk-organization }}
+            snyk monitor ${{ inputs.snyk-arguments }} \
+              --target-reference=${{ inputs.snyk-reference }} \
+              --org=${{ inputs.snyk-organization }}
           fi
